"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userAuthmiddleware_1 = __importDefault(require("../middleWare/userAuthmiddleware"));
const agentMiddleware_1 = __importDefault(require("../middleWare/agentMiddleware"));
const adminUserroute_1 = __importDefault(require("./admin/adminUserroute"));
const agentroute_1 = __importDefault(require("./agent/agentroute"));
const userRegistration_1 = __importDefault(require("./users/userRegistration"));
const userAuth_1 = __importDefault(require("./users/userAuth"));
const usersDetailsroute_1 = __importDefault(require("./users/usersDetailsroute"));
const pujaroute_1 = __importDefault(require("./pujas/pujaroute"));
const agentLogin_1 = __importDefault(require("./agent/agentLogin"));
const agentDetailsRoutes_1 = __importDefault(require("./agent/agentDetailsRoutes"));
const allUsers_1 = __importDefault(require("./admin/allUsers"));
const templeroute_1 = __importDefault(require("./temples/templeroute"));
const allTemples_1 = __importDefault(require("./temples/allTemples"));
const bookingroute_1 = __importDefault(require("./bookings/bookingroute"));
const submitReview_1 = __importDefault(require("./bookings/submitReview"));
const routes = (0, express_1.Router)();
routes.use("/admin", adminUserroute_1.default);
routes.use("/users", userAuthmiddleware_1.default, allUsers_1.default);
routes.use("/agent", userAuthmiddleware_1.default, agentroute_1.default);
routes.use("/agentlogin", agentLogin_1.default);
routes.use("/agentdetails", agentMiddleware_1.default, agentDetailsRoutes_1.default);
routes.use("/userregister", userRegistration_1.default);
routes.use("/userlogin", userAuth_1.default);
routes.use("/userdetails", userAuthmiddleware_1.default, usersDetailsroute_1.default);
routes.use("/booking", userAuthmiddleware_1.default, bookingroute_1.default);
routes.use("/puja", pujaroute_1.default);
routes.use("/temples", userAuthmiddleware_1.default, templeroute_1.default);
routes.use("/alltemples", allTemples_1.default);
routes.use("/reviews", userAuthmiddleware_1.default, submitReview_1.default);
exports.default = routes;
